import "./globals.css"; // styles for tailwind
import type { Metadata } from "next"; // meta data
import { Inter } from "next/font/google"; // font
import NavBar from "@/app/nav-bar";

// import the inter font
const inter = Inter({ subsets: ["latin"] });

// specify some meta data
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// define the layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className =
            "flex flex-col items-center justify-center mb-4 p-10 dark:bg-black bg-white")
        }
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
